### token获取
GET /WebReport/jk/ask/token HTTP/1.1
Host: 223.99.141.15:8080
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/137.0.0.0 Mobile/15E148 Safari/604.1

### 上传
POST /WebReport/jk/widgets/jsp/upload/upload.jsp HTTP/1.1
Host: 223.99.141.15:8080
token: 2tWgGpyMbP8weV9AS5ragA
Content-Type: multipart/form-data; boundary=xiaohuozichuishaoshao
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/137.0.0.0 Mobile/15E148 Safari/604.1

--xiaohuozichuishaoshao
Content-Disposition: form-data; name="keep"
Content-Type: text/plain

1234
--xiaohuozichuishaoshao
Content-Disposition: form-data; filename="qiqi.zip"; name="233333"
Content-Type: application/octet-stream

< C:/users/drunk/desktop/qiqi.zip
--xiaohuozichuishaoshao--

### 下载
GET /WebReport/jk/widgets/jsp/upload/download.jsp?file=chaochao.zip HTTP/1.1
Host: 223.99.141.15:8080
token: KyUEr4ewUAxHngBi49-qRQ
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/137.0.0.0 Mobile/15E148 Safari/604.1

### 本地测试下载
GET /jk/widgets/jsp/tools/download.jsp?file=1w.txt HTTP/1.1
Host: localhost:8080
token: CsLatgg4p2n5jsxyJrjOcw
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/137.0.0.0 Mobile/15E148 Safari/604.1

