# POST /file_upload_any HTTP/1.1
# POST /files_upload HTTP/1.1
POST /files_upload_any HTTP/1.1
Host: localhost:8081
Content-Type: multipart/form-data; boundary=ohmygod

--ohmygod
Content-Disposition: form-data; name="abc"; filename="teddy.jpg"
Content-Type: image/jpeg

< d:/fun/pic/teddy.jpg
--ohmygod
Content-Disposition: form-data; name="abc"; filename="es10.jpg"
Content-Type: image/jpeg

< d:/fun/pic/es10.jpg
--ohmygod
Content-Disposition: form-data; name="book"; filename="chinamobile.png"
Content-Type: image/png

< d:/fun/pic/chinamobile.png
--ohmygod
Content-Disposition: form-data; name="tip"
Content-Type: text/plain

I love teddy，使用express-demo目录下的upload.js上传文件
--ohmygod--